version: '3.3'

services:
  wordpress:
    image: wordpress:4.8
    restart: always
    ports:
      - 8097:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
