---
- name: Installation de Docker et deploiement image Ubuntu dedans
  hosts: production
  remote_user: root
  vars_files:
  - /etc/ansible/vars/default.yaml

  tasks:
  - name: Mise a jour de cache pour APT
    shell: 'apt update'
  - name: Installation pré-requis Docker
    apt: name={{ item }} state=latest
    loop: ['apt-transport-https', 'ca-certificates', 'curl',
           'software-properties-common', 'python3-pip', 'virtualenv',
           'python3-setuptools']
  - name: Création de la clée gpg pour Docker
    shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'
  - name: Ajout du depot sources.list
    shell: 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable" | tee /etc/apt/sources.list.d/docker.list'
  - name: Installation de Docker
    apt: update_cache=yes name=docker-ce state=latest
  - name: Installation de module Python pour Docker
    pip:
      name: docker
  - name: Creation de conteneur Ubuntu
    shell: "docker run -ti --name {{ container_name }} -d {{ container_image }} {{ container_command }}"